version: '3.8'

services:
  spark-tts-kk:
    build: .
    container_name: spark-tts-kk-app
    ports:
      - "8000:8000"
    volumes:
      - ./pretrained_models:/app/pretrained_models
      - ./static/outputs:/app/static/outputs
      - ./temp:/app/temp:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    environment:
      - TZ=Asia/Almaty
